version: v1.0
plan: standard
name: neetoCi
global_job_config:
  setup:
    - checkout
    - neetoci-version node 18.12
    - cache restore
    - yarn install
    - cache store
  jobs:
    - name: CiChecks
      commands:
        - .scripts/run_eslint_on_modified_files.sh
        - yarn test
